### ISSUE TITLE
suspectedCount（疑似病例）数值为0

### ISSUE THREAD

**Issue by bionexit** [BlankerL/DXY-COVID-19-Data#1]
这个值是因为不可描述原因留空？

**Comment by BlankerL** [comment]
不是的，是丁香园自4天前就没有继续公开省市级的suspectedCount数据了，可以参考BlankerL/DXY-2019-nCoV-Crawler#12 ，只有公开国家的数据。

具体原因我也不确定，可能是地方的卫健委没有发布这个数据了。

如果您有这个数据的数据来源可以通知我，我会对这个数据进行收录。
