### ISSUE TITLE
你好！数据还会更新吗

### ISSUE THREAD

**Issue by YW1028** [BlankerL/DXY-COVID-19-Data#100]
你好，该项目还会更新吗？

**Comment by BlankerL** [comment]
你好，非常感谢大家对这个数据库的支持。

目前，数据库放在阿里云上海的服务器当中，服务器配置较低，且上行带宽只有1Mbps，连接GitHub的延迟、丢包率都非常夸张。另外，目前数据库已经十分庞大，因此每次数据库上传行为都会对服务器造成毁灭性打击...

前段时间我在写自己的毕业论文，所以没有太多的精力维护数据上传的这部分任务。为了保证API接口的可用性，暂停了数据上传的任务。

我会在近期将数据库快照到海外服务器，并将数据上传的任务迁移到海外服务器上，以期能彻底解决这个问题。

为了保证API接口的可用性，我尽量将任务放在中国时间凌晨两点之后执行。

问题修复后会在这个Issue下进行更新，故将其他Issue暂时关闭。

---

更新：
服务器迁移完毕，数据更新已经恢复。每天凌晨12点开始在[Release](https://github.com/BlankerL/DXY-COVID-19-Data/releases)中更新，大约耗时30分钟。

**Comment by revelution-now** [comment]
感谢开发！目前我有最近一段时间更新的数目不大的数据需求，请问方便单独打包发给我吗？在这之后我会用您的 API 进行收集：）

**Comment by BlankerL** [comment]
> 感谢开发！目前我有最近一段时间更新的数目不大的数据需求，请问方便单独打包发给我吗？在这之后我会用您的 API 进行收集：）

抱歉，数据已经全部上传完成。如果没有意外，每天凌晨12点开始会在[Release](https://github.com/BlankerL/DXY-COVID-19-Data/releases)中更新，大约30分钟完成。

**Comment by cylindrical2002** [comment]
您好，Tags中找不到1.23-6.6之间的数据，请问它们在什么地方呢？
谢谢您的支持

**Comment by BlankerL** [comment]
现在的数据是每天更新全量数据，所以在最新的数据中能够下载到这个时间段内的数据。

1月23日到6月6日期间的更新应该是在[commits](https://github.com/BlankerL/DXY-COVID-19-Data/commits/master)里进行的，已经全部切换到[releases](https://github.com/BlankerL/DXY-COVID-19-Data/releases)里面发布了，直接在releases里下载[今天最新的版本](https://github.com/BlankerL/DXY-COVID-19-Data/releases/tag/2021.10.21)能找到那个时间段内的数据。
