### ISSUE TITLE
疫情新闻API接口更新暂停

### ISSUE THREAD

**Issue by kouteisang** [BlankerL/DXY-COVID-19-Data#105]
疫情新闻API接口只更新到6.7日，之后的新闻数据没有进行更新。

**Comment by BlankerL** [comment]
刚刚检查了数据库，数据应该没有暂停，但有文本缺失的现象，可以参考[此处](https://github.com/BlankerL/DXY-COVID-19-Crawler/issues/34#issuecomment-864442110)。

**Comment by BlankerL** [comment]
Duplicate of BlankerL/DXY-COVID-19-Crawler#34
