### ISSUE TITLE
疫情风险等级历史数据

### ISSUE THREAD

**Issue by iphone7725** [BlankerL/DXY-COVID-19-Data#106]
请问有没有国内疫情风险等级的历史数据

**Comment by iphone7725** [comment]
请问有些省市在一段时间内数据没有更新，是因为数据较之前没有变化吗？

**Comment by PeikaiLi** [comment]
请问您找到了风险登记的数据了吗

> 请问有些省市在一段时间内数据没有更新，是因为数据较之前没有变化吗？

**Comment by iphone7725** [comment]
风险等级的历史数据只能找到部分数据


可以参考公众号 疾控人，他们几乎每天都会发送中高风险等级地区





------------------ 原始邮件 ------------------
发件人: Peikai ***@***.***&gt;
发送时间: 2022年1月28日 16:41
收件人: BlankerL/DXY-COVID-19-Data ***@***.***&gt;
抄送: iphone7725 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [BlankerL/DXY-COVID-19-Data] 疫情风险等级历史数据 (#106)





 
请问您找到了风险登记的数据了吗
  
请问有些省市在一段时间内数据没有更新，是因为数据较之前没有变化吗？

**Comment by PeikaiLi** [comment]
> 风险等级的历史数据只能找到部分数据 可以参考公众号 疾控人，他们几乎每天都会发送中高风险等级地区
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: Peikai ***@***.***&gt; 发送时间: 2022年1月28日 16:41 收件人: BlankerL/DXY-COVID-19-Data ***@***.***&gt; 抄送: iphone7725 ***@***.***&gt;, Author ***@***.***&gt; 主题: Re: [BlankerL/DXY-COVID-19-Data] 疫情风险等级历史数据 (#106) 请问您找到了风险登记的数据了吗 请问有些省市在一段时间内数据没有更新，是因为数据较之前没有变化吗？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

非常感谢

**Comment by BlankerL** [comment]
所有数据都已经在API和数据仓库内展示，均来自于丁香园。
