### ISSUE TITLE
数据跟腾讯新闻的数据有差异，是为什么呢？

### ISSUE THREAD

**Issue by Hmeiliu** [BlankerL/DXY-COVID-19-Data#107]
比如，2021.12.15腾讯新闻现实的长春市的累积确诊是150例，但是我们2021.12.7更新的数据库当中长春市的累计确诊就已经163了

**Comment by BlankerL** [comment]
数据是丁香园网页中返回的数据，具体数据差异应该是腾讯新闻和丁香园的数据来源不一致。
