### ISSUE TITLE
请问这个项目还维护么？丁香园的H5地址更新了

### ISSUE THREAD

**Issue by chenqingspring** [BlankerL/DXY-COVID-19-Data#112]
新（有数据）：https://ncov.dxy.cn/ncovh5/view/pneumonia
老（无数据）：https://3g.dxy.cn/newh5/view/pneumonia

**Comment by chenqingspring** [comment]
新（有数据）：https://ncov.dxy.cn/ncovh5/view/pneumonia
老（无数据）：https://3g.dxy.cn/newh5/view/pneumonia

**Comment by BlankerL** [comment]
感谢反馈，可能是出于对本项目的照顾，丁香园原始的网站仍然能够请求并且成功获取数据。

之前或许由于大家毕业设计的压力较大，又出现了对服务器的大规模请求，导致数据库有异常，数据仓库的上传被多次中断。同时，由于API和数据库部署在腾讯云上海，服务器配置低且对GitHub连接稳定性较差，数据导出和上传资源开销极大。

目前我已经将数据仓库拆分到海外服务器，对API访问效率略有影响，但配置和上行带宽充裕，能够保证数据仓库稳定更新。

最近我也会持续关注数据仓库的上传稳定性，保证尽量不断更，再次感谢反馈！
