### ISSUE TITLE
数据从2022-11-21起更新停止

### ISSUE THREAD

**Issue by Ryanna-github** [BlankerL/DXY-COVID-19-Data#117]
每日自动运行结果数据从2022-11-21起更新停止

**Comment by PraisingJ** [comment]
是什么原因啊

**Comment by BlankerL** [comment]
大家好，目前数据已经恢复更新。

### 断更说明
由于目前国内请求量更大，同时丁香园的API接口禁止境外请求，因此API和爬虫放在中国境内的服务器上。

然而，中国境内服务器上行带宽有限，同时几乎无法访问GitHub API，所以把数据库和GitHub Release上传脚本放在了境外服务器上，并只做数据库和上传用途，没有做其他用途。

大概在一个星期之前（11月21日），境外的这个服务器被墙了（不是端口被封，而是直接无法ping通），所以API和爬虫都无法正常访问到数据库内数据...目前通过一台跳板机转发了流量，保证境内服务器能够正常触达境外数据库。

之后计划把爬虫脚本放在境外服务器，并把爬虫请求转发到境内服务器发送，至少保证爬虫能够稳定运行并录入数据，未来考虑在访问量降低后把API也迁移到境外。

**Comment by Ryanna-github** [comment]
> 大家好，目前数据已经恢复更新。
> 
> ### 断更说明
> 由于目前国内请求量更大，同时丁香园的API接口禁止境外请求，因此API和爬虫放在中国境内的服务器上。
> 
> 然而，中国境内服务器上行带宽有限，同时几乎无法访问GitHub API，所以把数据库和GitHub Release上传脚本放在了境外服务器上，并只做数据库和上传用途，没有做其他用途。
> 
> 大概在一个星期之前（11月21日），境外的这个服务器被墙了（不是端口被封，而是直接无法ping通），所以API和爬虫都无法正常访问到数据库内数据...目前通过一台跳板机转发了流量，保证境内服务器能够正常触达境外数据库。
> 
> 之后计划把爬虫脚本放在境外服务器，并把爬虫请求转发到境内服务器发送，至少保证爬虫能够稳定运行并录入数据，未来考虑在访问量降低后把API也迁移到境外。

感谢！
