### ISSUE TITLE
为什么"疑似"病例非常少?

### ISSUE THREAD

**Issue by YancyW** [BlankerL/DXY-COVID-19-Data#13]
所有记录里几乎都没有"疑似"病例(province_suspectedCount),   "疑似"一栏下几乎都是0, 偶尔出现的"疑似"数量几乎就是1或2个,  比新浪等的数据少非常多.
请问是丁香园上面的数据就没有疑似吗?

**Comment by BlankerL** [comment]
Duplicate of #1
