### ISSUE TITLE
English version of Area Data -  DXYArea.csv

### ISSUE THREAD

**Issue by dmahasen** [BlankerL/DXY-COVID-19-Data#19]
Hi,
Thank you for sharing this dataset. But it would be great if you can provide the dataset with the names of cities and provinces in English. 

Thank you,

Best Regards,

Mahasen

**Comment by BlankerL** [comment]
Hi. I will check if there is any project mapping the Chinese provinces/cities name into English. If I could find some kind of Chinese-to-English mapping, I will offer an English dataset.

**Comment by BlankerL** [comment]
Maybe I can also find some workaround. For example, I will try to map the Chinese city name into zip code, and map the zip code into corresponding English name. 

Anyway, I will give it a try and give you a feedback.

**Comment by dmahasen** [comment]
Thank you very much for your suggestions. :)

**Comment by BlankerL** [comment]
Hello, the `locationId` is now available for latest data because Ding Xiang Yuan directly provides it. I will backtrack all the historical data and add `locationId` for them. I suppose the English version of DXYArea will be available soon.

**Comment by BlankerL** [comment]
`locationId` is available for all city-level data in China and country-level data in countries other than China (by using API). 
`locationId` in China is the zip code of the city. The definition of `locationId` in other countries is not figured out yet. 
If it is convenient for you, you can just use `locationId` to do the research at first. I will update the English version of city name as soon as possible.

You can refer to [here](https://github.com/BlankerL/DXY-COVID-19-Crawler/issues/31#issuecomment-580734921) for more information.

**Comment by dmahasen** [comment]
Hi,

I found the list of English names of cities in China.  https://github.com/jianxu305/nCov2019_analysis/blob/master/src/locationDict.csv.

I can use this to do the translation. 

Thank you for your help. :)

**Comment by BlankerL** [comment]
> Hi,
> 
> I found the list of English names of cities in China. https://github.com/jianxu305/nCov2019_analysis/blob/master/src/locationDict.csv.
> 
> I can use this to do the translation.
> 
> Thank you for your help. :)

Sure, you can use this. I suppose this is not up-to-date, the latest modified time was 3 days ago. With new cities coming into the database, it might not follow up.

I am trying to make a mapping for the zip code to English name of those cities, and already found some solutions. I will try to implement it tomorrow.

**Comment by BlankerL** [comment]
English city names are all available now.

**Comment by Dobby233Liu** [comment]
Resolved (?) by BlankerL/DXY-COVID-19-Crawler#61

**Comment by BlankerL** [comment]
> Resolved (?) by [BlankerL/DXY-COVID-19-Crawler#61](https://github.com/BlankerL/DXY-COVID-19-Crawler/issues/61)

Yep, complete most of the work, I will mention the changes in that issue.
