### ISSUE TITLE
2019-ncov累计数据问题

### ISSUE THREAD

**Issue by economic-riem** [BlankerL/DXY-COVID-19-Data#2]
冒昧的想问下：
1、截至2020年1月29日（10：00-23：00之间都行），累计确诊人数的数据，在哪里找啊？
2、截至2020年1月30日（10：00-23：00之间都行），累计确诊人数的数据，在哪里找啊？
谢谢啊！

**Comment by BlankerL** [comment]
全国累计数据的时间序列在[DXYOverall.csv](https://github.com/BlankerL/DXY-2019-nCoV-Data/blob/master/DXYOverall.csv)中提供，updateTime是UNIX时间戳，可以通过转换时间戳查看数据更新时间。

下一个版本我会将updateTime转换会 YYYY-MM-DD HH:MM:SS 的格式，方便各位使用。

**Comment by BlankerL** [comment]
TODO
1. 将updateTime转换会 YYYY-MM-DD HH:MM:SS 的格式

**Comment by economic-riem** [comment]
不好意思，我没表述清楚，想要的是：
1，截止2020年1月29日（10：00-23：00之间都行），全国各个城市的累计确诊人数的数据，在哪里找啊？
2，截止2020年1月30日（ 10：00-23：00之间都行），全国各个城市的累积确诊人数的数据，在哪里找啊？
谢谢啊！

**Comment by BlankerL** [comment]
> 不好意思，我没表述清楚，想要的是：
> 1，截止2020年1月29日（10：00-23：00之间都行），全国各个城市的累计确诊人数的数据，在哪里找啊？
> 2，截止2020年1月30日（ 10：00-23：00之间都行），全国各个城市的累积确诊人数的数据，在哪里找啊？
> 谢谢啊！

地区数据在[DXYArea.csv](https://github.com/BlankerL/DXY-2019-nCoV-Data/blob/master/DXYArea.csv)中有，建议使用之前先查看[README](https://github.com/BlankerL/DXY-2019-nCoV-Data)

**Comment by economic-riem** [comment]
收到，看懂了，谢谢啊
