### ISSUE TITLE
您的项目已录入 OpenSourceWuhan 武汉开源

### ISSUE THREAD

**Issue by WeileiZeng** [BlankerL/DXY-COVID-19-Data#20]
您好！

感谢您对武汉和开源社区的贡献，您的项目已录入 OpenSourceWuhan 武汉开源,如有疑问请[open an issue](https://github.com/WeileiZeng/OpenSourceWuhan)

武汉开源 [OpenSourceWuhan](https://weileizeng.github.io/OpenSourceWuhan/)
集齐了开源平台上支援武汉的项目，是一个连结各个开源项目的入口。

站点：
[https://weileizeng.github.io/OpenSourceWuhan/](https://weileizeng.github.io/OpenSourceWuhan/)

**Comment by BlankerL** [comment]
万分感谢！

这个项目和[爬虫项目](https://github.com/BlankerL/DXY-2019-nCoV-Crawler)的README里有其他的基于我的项目而做的可视化等工具，如果要收录可以参考一下。

同时，[API](https://lamb.isaaclin.cn/nCoV/)比起这个项目的静态数据，可能会更方便其他人二次开发。

**Comment by WeileiZeng** [comment]
谢谢说明！我把两个项目和api的链接都一起给了

**Comment by WeileiZeng** [comment]
readme里的可视化项目也已经加入，谢谢提供信息！

**Comment by BlankerL** [comment]
感谢收录！
