### ISSUE TITLE
2020-02-03 data abnormally

### ISSUE THREAD

**Issue by jianxu305** [BlankerL/DXY-COVID-19-Data#21]
Feb 3 CSV data contains logically duplicated entries with cityName "南阳" and "南阳（含邓州）", "商丘" and "商丘（含永城）", etc,   The effect is the counts aggregated on province level will be too large on Feb 3.

If this project doesn't clean this data, then probably better to notify users so that they can be aware of this.  Thanks.

**Comment by Dobby233Liu** [comment]
It is better to report noise data in BlankerL/DXY-2019-nCoV-Crawler#34

**Comment by BlankerL** [comment]
Thank you for your report. These data do not contain noise and will not be removed. I will add a file to remind the users to take care.

**Comment by BlankerL** [comment]
I have mentioned this in README file. Thanks again.

**Comment by Furienli** [comment]
May I ask whether the Data in the JSON folder under the DXY-COVID-19-Data project will not be updated any more? I requested dXYArea-Timeseries. The JSON Data was found only on July 16th

**Comment by BlankerL** [comment]
> May I ask whether the Data in the JSON folder under the DXY-COVID-19-Data project will not be updated any more? I requested dXYArea-Timeseries. The JSON Data was found only on July 16th

Yes, I will fix the problem ASAP. I am moving from HK to BJ recently, I will fix the problem when everything is settled down.
