### ISSUE TITLE
[2020-02-09 08:10:06.607] 的死亡数据错误

### ISSUE THREAD

**Issue by wifecooky** [BlankerL/DXY-COVID-19-Data#22]
"3795" 应该是多了个 3。

----
'https://img1.dxycdn.com/2020/0208/356/3395436496692894611-135.png', 'https://img1.dxycdn.com/2020/0208/599/3395474215095538530-135.png', 'https://img1.dxycdn.com/2020/0208/502/3395474230127927756-135.png', 'https://img1.dxycdn.com/2020/0208/704/3395474279520515356-135.png', 'https://img1.dxycdn.com/2020/0208/629/3395474292405418005-135.png']",,,36833,27657,2602,3795,6101.0,,,,,,该字段已替换为说明1,易感人群：人群普遍易感。老年人及有基础疾病者感染后病情较重，儿童及婴幼儿也有发病,潜伏期：一般为 3～7 天，最长不超过 14 天，潜伏期内可能存在传染性，其中无症状病例传染性非常罕见,宿主：野生动物，可能为中华菊头蝠,,,病毒：新型冠状病毒 2019-nCoV,传染源：新冠肺炎的患者。无症状感染者也可能成为传染源。,传播途径：经呼吸道飞沫、气溶胶传播、接触传播是主要的传播途径。消化道等传播途径尚待明确。,疑似病例数来自国家卫健委数据，目前为全国数据，未分省市自治区等,,[],2020-02-09 08:10:06.607

**Comment by BlankerL** [comment]
确认有误，由于[云南省“待明确地区”死亡人数录入为2990导致](https://github.com/BlankerL/DXY-2019-nCoV-Crawler/issues/34#issuecomment-583825139)，已移除。

**Comment by BlankerL** [comment]
数据错误请移步 BlankerL/DXY-2019-nCoV-Crawler#34 提交。

**Comment by earthcli** [comment]
黑龙江省 | 齐齐哈尔 | 227 | 0 | 8 | 3 | 277 | 0 | 0 | 0 | 2020/2/7 9:01
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --


277数值有误!

**Comment by BlankerL** [comment]
> 黑龙江省 	齐齐哈尔 	227 	0 	8 	3 	277 	0 	0 	0 	2020/2/7 9:01
> 
> 277数值有误!

丁香园没有校正，您认为应该是多少？
