### ISSUE TITLE
异常提交

### ISSUE THREAD

**Issue by cxdluckly** [BlankerL/DXY-COVID-19-Data#24]
您好，开发者，我发现在您的CSV文件夹下的有关各个省份的数据中没有香港，台湾与澳门的数据，但在API测试中是有的。期待您的回复，谢谢。

**Comment by BlankerL** [comment]
静态数据方面的问题放到这边吧，我在README文件里已经说明了：
> 其中：地区数据DXYArea.csv仅包括丁香园中国地区精确至地级市的数据，港澳台/西藏的数据精确度仅到省级，不包含在此文件中。如有需要可以修改脚本内Listen类的dumper函数，来自定义数据提取的存储方式。
