### ISSUE TITLE
作者你好，想问下currentConfirmedCount是什么  confirmedCount是确诊人数，看了下接口文档里没写currentConfirmedCount，单词意思是 当前确认数

### ISSUE THREAD

**Issue by woxixiuqiangwei** [BlankerL/DXY-COVID-19-Data#28]

**Comment by BlankerL** [comment]
抱歉，我近期会更新接口文档。`currentConfirmedCount`是现存确诊人数，数值应该是累计确诊人数`confirmedCount`减去死亡人数`deadCount`再减去治愈人数`curedCount`。

**Comment by woxixiuqiangwei** [comment]
> 抱歉，我近期会更新接口文档。`currentConfirmedCount`是现存确诊人数，数值应该是累计确诊人数`confirmedCount`减去死亡人数`deadCount`再减去治愈人数`curedCount`。

嗯嗯好的
