### ISSUE TITLE
好像没看到台湾的数据

### ISSUE THREAD

**Issue by vip2193** [BlankerL/DXY-COVID-19-Data#32]

**Comment by BlankerL** [comment]
使用前请先阅读README
> 其中：地区数据DXYArea.csv仅包括丁香园中国地区精确至地级市的数据，港澳台/西藏的数据精确度仅到省级，不包含在此文件中。如有需要可以修改脚本内Listen类的dumper函数，来自定义数据提取的存储方式。

**Comment by BlankerL** [comment]
Duplicate of #16
