### ISSUE TITLE
请问是否可以按日期存储数据

### ISSUE THREAD

**Issue by duwensi** [BlankerL/DXY-COVID-19-Data#34]
感谢作者的付出。
目前json/csv中只有最新的数据。
请问是否可以将数据按日期存储在json/csv目录下，结合gitcdn，对于缓解服务器压力、节省作者服务器开支以及提升数据使用的便捷性都有益处。

**Comment by Dobby233Liu** [comment]
你的意思是按日期*分割*数据？

**Comment by duwensi** [comment]
> 你的意思是按日期_分割_数据？

是的。比如：
```
json/
    ├── latest/
    |       ├── news.json
    |       ├── overall.json
    |       ├── area.json
    |       └── rumors.json
    ├── 2020-02-17/
    |       ├── news.json
    |       ├── overall.json
    |       ├── area.json
    |       └── rumors.json
    └── .../
```

**Comment by Dobby233Liu** [comment]
仓库一天<a href="https://github.com/BlankerL/DXY-COVID-19-Data/commits/master">更新<span title="24"><ins>上十遍</ins></span></a>，要是真的分割似乎整个仓库要乱

**Comment by BlankerL** [comment]
你好，目前CSV文件中包含**所有时间序列数据，而非仅有最新数据**，JSON文件中**仅包含最新数据**（部分用户希望稳定请求并获取最新数据，这个项目成立之初API并不太稳定）。

如果希望获得完整的时间序列数据，直接通过API请求`/nCoV/api/area?latest=0`即可获得，我也看过logfile，有此需求的用户实际上是极少数。

另外，想请问一下是什么功能需要单独按日期来储存/读取JSON呢？如果真的希望获得完整的数据，请求上述API之后在本地对`updateTime`字段进行排序似乎就可以完成，且数据库内几乎已经是顺序排列好的数据了。

**Comment by duwensi** [comment]
我只看了json里边的，以为csv也是只有最新的，那我调用csv的数据另行处理就可以。谢谢。

**Comment by BlankerL** [comment]
> 我只看了json里边的，以为csv也是只有最新的，那我调用csv的数据另行处理就可以。谢谢。

感谢，CSV为了方便科研用途，包含所有历史数据，但是不包括港澳台及国外地区数据，具体可以参考[README](https://github.com/BlankerL/DXY-COVID-19-Data#2019%E6%96%B0%E5%9E%8B%E5%86%A0%E7%8A%B6%E7%97%85%E6%AF%92%E7%96%AB%E6%83%85%E6%97%B6%E9%97%B4%E5%BA%8F%E5%88%97%E6%95%B0%E6%8D%AE%E4%BB%93%E5%BA%93)。
