### ISSUE TITLE
suspectedCount in DXYArea.json are all 0

### ISSUE THREAD

**Issue by denven** [BlankerL/DXY-COVID-19-Data#35]
Not consistent with data other files and it's also  not correct right now.

**Comment by BlankerL** [comment]
Ding Xiang Yuan has not published any of province-level or city-level suspectedCount since January 28. I do not check the government published data, but I suppose it is because the Provincial/City-Level Health Commissions do not publish them.

**Comment by BlankerL** [comment]
Duplicate of #1
