### ISSUE TITLE
csv文件中添加国外、香港和台湾的数据

### ISSUE THREAD

**Issue by yiluheihei** [BlankerL/DXY-COVID-19-Data#39]
谢谢您的项目，有两个问题请教您一下

因为之前是分析从 api 得到的数据，好像外网访问 api 不太稳定，现在想添加一种方法读取这个数据仓库中的 csv 文件。为了跟 api 返回的数据一致，能不能在area文件中

1. 把csv中包含国外、香港和台湾的数据
2. 然后加上countryName和coutryEnglishName列
3. 添加provinceShortName列

谢谢

**Comment by BlankerL** [comment]
之前API部署在香港，但是大陆地区访问极其不稳定，因此将API迁移至大陆的服务器了。

我最近开学了，空闲时间比较少，因此在短期内可能无法对脚本进行修改。在[script.py](https://github.com/BlankerL/DXY-COVID-19-Data/blob/master/script.py)中有数据处理的完整脚本，如果有额外的数据处理需求，可以对脚本稍微改动，就能够得到你想要的数据集（脚本的逻辑可以参考BlankerL/DXY-COVID-19-Crawler#67）。

**Comment by yiluheihei** [comment]
谢谢，我用 R 处理了从api下载的数据，得到了自己想要的数据
对  python 不熟悉， 不然就用python做 个 PR 了

**Comment by sarahwang93** [comment]
这部分现在有人在做吗 求数据啊

**Comment by mashuai191** [comment]
我也是需要世界范围的数据，如果作者忙，只有自己看代码了。
同时感谢作者提供这么好的数据源. 目前基于这个数据源在kaggle上做了一个传染病模型https://www.kaggle.com/mashuai191/coronavirus-2019-prediction-new-model

**Comment by mashuai191** [comment]
看了一下csv 文件里面是有国外总体数据的， 在foreignStatistics那一列，从2/29号开始有这个数据，因为是直接存的json格式需要自己转一下

**Comment by BlankerL** [comment]
> 看了一下csv 文件里面是有国外总体数据的， 在foreignStatistics那一列，从2/29号开始有这个数据，因为是直接存的json格式需要自己转一下

感谢支持！这部分数据是丁香园在28日19:50左右更新网站后提供的，历史数据暂时不全。
我会尽量在未来两天内把所有历史数据补全到DXYArea.csv文件中，但是由于时间有限可能无法及时更新，更新后会在此处通知。

**Comment by BlankerL** [comment]
> 谢谢，我用 R 处理了从api下载的数据，得到了自己想要的数据
> 对 python 不熟悉， 不然就用python做 个 PR 了

感谢支持，似乎有挺多人有这个需求，我尽量会在2天内更新这部分数据。

**Comment by sarahwang93** [comment]
多谢数据提供！ 但是我做了一下filter 感觉数据有缺失 国外数据我再找找看 我自己做的可视化用的是tableau 美观一点

**Comment by BlankerL** [comment]
> 多谢数据提供！ 但是我做了一下filter 感觉数据有缺失 国外数据我再找找看 我自己做的可视化用的是tableau 美观一点

数据是实时获取丁香园的数据。认为数据缺失，可能是因为当天该国疫情数据并没有更新，需要查找上一次更新的时间。这个数据的updateTime是数据更新的时间，并不是每一天每一个国家都有条目在更新的。

**Comment by yiluheihei** [comment]
把自己做的area的csv文件上传到[这里了](https://github.com/yiluheihei/nCoV-2019-Data/blob/master/ncov_area.csv)。包含了国外数据，目前设置的是从上午9点到0点，每隔3小时更新一次！

跟作者的稍有不同：作者的数据是每一行province的数据与city的数据放在一起，用`province_`和`city_`前缀辨别；我做的数据是把province的数据单独放置在一行，省去了`province_`和`city_`前缀，直接用api中变量名表示.

**Comment by BlankerL** [comment]
自[`4db432f`](https://github.com/BlankerL/DXY-COVID-19-Data/commit/4db432fda233a701a3a7569e08ab20db083987b1)起，海外及港澳台数据也一并推送至csv文件中。
