### ISSUE TITLE
同步 json 格式的文件

### ISSUE THREAD

**Issue by yarray** [BlankerL/DXY-COVID-19-Data#4]
您好，我是 [Wuhan2020](https://github.com/wuhan2020/) 那边的参与者，最近在用您抓取的数据制图。

请问是否可以也在此仓库中同步 json 格式的文件？

https://lab.isaaclin.cn/nCoV/ 应该是压力比较大，一直不敢太用只是每天更新，但是现在也访问不了了... 在这个仓库有 json 格式文件的话可能可以缓解 api 的访问压力。有

```
https://lab.isaaclin.cn/nCoV/api/area
https://lab.isaaclin.cn/nCoV/api/area?latest=0
https://lab.isaaclin.cn/nCoV/api/overall?latest=0
```

这几个我觉得就能覆盖大多数应用了。

感谢！

**Comment by BlankerL** [comment]
按小时频率同步能否满足要求？

**Comment by yarray** [comment]
可以的，主要是用来制图

**Comment by BlankerL** [comment]
> 可以的，主要是用来制图

尽量会在今天完成，同时API域名已经完成备案，今天应该会迁移至大陆服务器，可以考虑使用API来提取数据。

**Comment by yarray** [comment]
> 尽量会在今天完成，同时API域名已经完成备案，今天应该会迁移至大陆服务器，可以考虑使用API来提取数据。

啊那太好了，感谢！

**Comment by BlankerL** [comment]
> > 尽量会在今天完成，同时API域名已经完成备案，今天应该会迁移至大陆服务器，可以考虑使用API来提取数据。
> 
> 啊那太好了，感谢！

API已经完成迁移，目前的响应速度在300ms以内，我也会尽量在今天完成json文件的推送。

**Comment by BlankerL** [comment]
> > 尽量会在今天完成，同时API域名已经完成备案，今天应该会迁移至大陆服务器，可以考虑使用API来提取数据。
> 
> 啊那太好了，感谢！

已经完成，数据位于目录[json](https://github.com/BlankerL/DXY-2019-nCoV-Data/tree/master/json)中。

麻烦您测试一下看看能否正常使用，如果有问题请和我说～
