### ISSUE TITLE
不方便对CSV文件进行处理的可以看下这个已经按省份和地区分类存放好的数据仓库

### ISSUE THREAD

**Issue by zyq5945** [BlankerL/DXY-COVID-19-Data#40]
[csv格式](https://github.com/zyq5945/DXY-COVID-19-Data-Arrange-CSV)

[数组json格式](https://github.com/zyq5945/DXY-COVID-19-Data-Arrange-ajson)

[字典json格式](https://github.com/zyq5945/DXY-COVID-19-Data-Arrange-djson)

可以直接加载homepage 上json为前端所使用，比如

[海南的详细情况](https://zyq5945.github.io/DXY-COVID-19-Data-Arrange-DJSON/data/ParentDetail/%E6%B5%B7%E5%8D%97.json)

**Comment by BlankerL** [comment]
感谢，已经添加`good first issue`标签。
