### ISSUE TITLE
Doube quote missing!

### ISSUE THREAD

**Issue by adr75** [BlankerL/DXY-COVID-19-Data#44]
Hi,
There's a double quote missing in DXYArea.json line 475.
Adrien

**Comment by tduffy-saf** [comment]
Yep. It's causing things to break.

**Comment by BlankerL** [comment]
Hello, 

Thanks. The file is automatically dumped and generated by `json` package, I have no idea why this will happen. Currently looking for the reasons.

**Comment by BlankerL** [comment]
Thanks, I have already fixed the problem. More details are available in #47.

**Comment by adr75** [comment]
Thanks very much @BlankerL
