### ISSUE TITLE
您好，接口好像失效了，网站也打不开了

### ISSUE THREAD

**Issue by wmathor** [BlankerL/DXY-COVID-19-Data#47]

**Comment by tduffy-saf** [comment]
Yes, I am unable to open the website as well. The DXYArea.json file is also broken. A double-quote is missing from the Nepal entry.

**Comment by BlankerL** [comment]
是的，我刚刚才看到消息，目前正在查找原因。

**Comment by BlankerL** [comment]
> Yes, I am unable to open the website as well. The DXYArea.json file is also broken. A double-quote is missing from the Nepal entry.

Sorry for that, I am currently looking for the reason. The DXYArea.json is automatically generated, I have no idea why it will break.

**Comment by BlankerL** [comment]
@wmathor 已经恢复，问题在于script.py文件在载入json文件时出错，由于后端设置了循环执行任务，导致MongoDB失去响应，目前已经解决。

---

@tduffy-saf Bug fixed. The problem is that the script.py file has an error when loading the json file. Due to the cyclic execution task set in the backend, MongoDB has become unresponsive, which has been resolved.
