### ISSUE TITLE
Redundant data

### ISSUE THREAD

**Issue by jnasoy** [BlankerL/DXY-COVID-19-Data#48]
I noticed this consolidated data for whole China

![image](https://user-images.githubusercontent.com/7227288/76729094-59a41380-6793-11ea-8170-99a7b365ae2a.png)

Can possible removed because there are already data for China per Province?

**Comment by BlankerL** [comment]
DXY has entries of both China (national-level) and province-level data, can you please simply remove this entry if you do not need it? Maybe others will need this piece of information.
