### ISSUE TITLE
版权咨询

### ISSUE THREAD

**Issue by raynerr** [BlankerL/DXY-COVID-19-Data#49]
您好，十分感谢您可以在该平台提供如此丰富的数据内容。
近期，我们准备利用COVID-19数据做相关研究，请问是否可以直接使用您提供的数据？您是否有一些其他要求？烦请告知，谢谢！

**Comment by BlankerL** [comment]
您好，本项目遵循MIT协议，使用时请直接参照[使用条款](https://zh.wikipedia.org/wiki/MIT%E8%A8%B1%E5%8F%AF%E8%AD%89)即可，使用时仅需附带本项目著作声明。
