### ISSUE TITLE
json数据像csv数据那样提供所有数据

### ISSUE THREAD

**Issue by yiluheihei** [BlankerL/DXY-COVID-19-Data#50]
你好

我觉得可以像csv数据那样json数据也提供所有数据，或者说可以提供两个版本一个`latest=0`，一个是`latest=1`，目前json版本只是提供的最新版数据。

因为您提供csv数据字段并不像json中那么全，比如关于国家的字段`country*`, 这样如果需要得到所有数据就得用api，会无形中给api访问带来压力。如果json数据也是提供所有的数据，就可以直接根据json自定制自己想要的数据格式，或者是某些字段，而不用访问api，减小api压力。

**Comment by BlankerL** [comment]
你好，感谢反馈，目前已经在csv文件中补全大部分字段。出于分流的目的，我也考虑将时间序列数据的json文件推送上来。

**Comment by BlankerL** [comment]
DXYOverall和DXYArea数据库的时间序列数据已经推送至数据仓库[json文件夹](https://github.com/BlankerL/DXY-COVID-19-Data/tree/master/json)内，同时取消API内这`/nCoV/api/overall`及`/nCoV/api/area`的支持。
