### ISSUE TITLE
新生成的数据格式似乎有错乱

### ISSUE THREAD

**Issue by zyq5945** [BlankerL/DXY-COVID-19-Data#55]
你好，新生成的csv数据格式似乎有错乱，一会updateTime字段在中间，一会格式又会变成在最后，在中间的时候数量又变成浮点型了。是不是开了两个定时任务在处理了。

**Comment by BlankerL** [comment]
是每一次下载的数据，updateTime列位置不对吗？还是两行数据之间都有偏差？

**Comment by zyq5945** [comment]
你比对下18日13:54和14:54生成的csv版本就清楚了。

**Comment by BlankerL** [comment]
所有数值储存为整形，所有日期储存为yyyy-mm-dd HH:MM:SS。
updateTime列位置在文件内保持一致，仅在文件间不一致，不会影响数据处理，不作调整。
