### ISSUE TITLE
数据和卫健委发布数据不相同

### ISSUE THREAD

**Issue by xcy96** [BlankerL/DXY-COVID-19-Data#58]
以DXYOverall.json这个文件来说，我通过git拉下来每天最后一次提交的数据文件当做这一天的数据，但是却跟第二天的卫健委数据有冲突。
![image](https://user-images.githubusercontent.com/31194211/77174581-3d3e0900-6afc-11ea-8350-4db63b75f5dd.png)
比如说这个是3.18最后一次的数据，新增确诊病例86例，新增死亡病例11例，新增疑似病例12例。
![image](https://user-images.githubusercontent.com/31194211/77174642-5941aa80-6afc-11ea-8399-752cdc166b8a.png)
zhegeshiweijianw这个是卫健委的数据，新增确诊病例34例，新增死亡病例8例（湖北8例），新增疑似病例23例。
可见两份数据有较大差异

**Comment by BlankerL** [comment]
我并没有针对每一份数据进行核对，数据的获取工作全部由爬虫自动化进行。爬虫的数据来源是丁香园，丁香园上标注的数据来源是卫建委。因为丁香园的数据更新频率远高于卫建委的数据更新频率，或许不应该用当天的最后一份数据，而是日中或第二天的数据才能够与卫建委匹配？
