### ISSUE TITLE
请问能否提供一个每天的汇总省市数据？

### ISSUE THREAD

**Issue by chuxiang93** [BlankerL/DXY-COVID-19-Data#6]
如题，目前只有实时数据，能否提供每天的省市数据？

**Comment by 13625919003** [comment]
下载数据仓库里面的数据是时间序列的，有从1月至今的全部数据，每天更新的数据是在原有的表格上新增项目

**Comment by BlankerL** [comment]
目前数据仓库内均为时间序列数据，最简单的Excel处理也能轻松获取你所需要的每日省市数据。
