### ISSUE TITLE
为何3.27日数据没有刷新？请查

### ISSUE THREAD

**Issue by casterking** [BlankerL/DXY-COVID-19-Data#63]
目前看到最后一次更新是26日晚的数据

**Comment by BlankerL** [comment]
GitHub在中国受到中间人攻击，而项目的服务器在中国大陆，因此数据推送不到数据仓库内。我已经手动更新了一次数据，稍后查找合适的解决方案。
GitHub遭受中间人攻击可参考：https://www.zhihu.com/question/382718053

---

GitHub is suffering a man-in-the-middle attack in mainland China area, where the server is located, so the data cannot be pushed into the data warehouse.

**Comment by casterking** [comment]
好的，收到刷新。感谢！

**Comment by BlankerL** [comment]
我确认了一下，目前攻击应该已经结束了，数据仓库推送已经恢复正常。

**Comment by BlankerL** [comment]
q
