### ISSUE TITLE
json和csv里面的新闻最新都只到0327了，后面的没有了

### ISSUE THREAD

**Issue by hungleung** [BlankerL/DXY-COVID-19-Data#67]
json和csv里面的新闻最新都只到0327了，后面的没有了
是哪里出了问题还是后续不再更新

**Comment by crazyYG** [comment]
同问，API里面新闻数据也同样没有了只到0327

**Comment by BlankerL** [comment]
感谢反馈，个人认为是丁香园修改了数据返回结构，我马上进行确认。

**Comment by BlankerL** [comment]
丁香园停止更新英文的新闻，并且在数据返回时删除了provinceId字段，导致API返回数据错误过滤了。

自[`fdf9685`](https://github.com/BlankerL/DXY-COVID-19-Data/commit/fdf968579adebf30ad5ffdab6c0c6504baa0c954)起，API和数据仓库的新闻部分均已经恢复正常。
