### ISSUE TITLE
数据源中provinceName:中国的问题

### ISSUE THREAD

**Issue by SueHsia** [BlankerL/DXY-COVID-19-Data#72]
在DXY-Area-TimeSeries.json中，
3月15号以后的数据中有provinceName:中国这一数据
3月15号以前的数据中没有provinceName:中国这一条，导致对中国的数据进行可视化时会出现麻烦

**Comment by BlankerL** [comment]
你好，应该可以使用`"countryName": "中国"`来完成索引，`"provinceName": "中国"`或许是丁香园在3.15之后添加的字段。
