### ISSUE TITLE
可以附加重症数据吗？

### ISSUE THREAD

**Issue by lsy1262914003** [BlankerL/DXY-COVID-19-Data#73]
请求附加重症数据

**Comment by BlankerL** [comment]
我并不太理解你需要什么重症数据？

丁香园在之前两个月有持续更新重症数据，并且已经在数据仓库中了。自从疫情出现拐点并且多地市疫情结束之后，丁香园已经取消了重症数据的显示。

本项目只收录丁香园提供的数据，并没有额外收集整理其他数据。丁香园的数据来源应该是国家和各地市卫建委，如果丁香园/卫建委中任何一方不提供这份数据，则本数据仓库中就收录不到这份数据。

**Comment by lsy1262914003** [comment]
就是重症患者数目，丁香园确实后面取消显示重症患者，但国家卫健委仍然在给出重症数据

**Comment by BlankerL** [comment]
> 就是重症患者数目，丁香园确实后面取消显示重症患者，但国家卫健委仍然在给出重症数据

抱歉，本项目没有针对国家卫建委采集数据。
