### ISSUE TITLE
疑似病例数很多都是零

### ISSUE THREAD

**Issue by jianxu305** [BlankerL/DXY-COVID-19-Data#8]
前面有人提过， Issue closed 了，但是问题并没有解决。这是什么原因？

**Comment by Dobby233Liu** [comment]
Duplicate of #1

> 不是的，是丁香园自4天前就没有继续公开省市级的suspectedCount数据了，可以参考BlankerL/DXY-2019-nCoV-Crawler#12 ，只有公开国家的数据。
> 
> 具体原因我也不确定，可能是地方的卫健委没有发布这个数据了。
> 
> 如果您有这个数据的数据来源可以通知我，我会对这个数据进行收录。

**Comment by BlankerL** [comment]
Duplicate of #1
