### ISSUE TITLE
历史数据不全

### ISSUE THREAD

**Issue by LiZHU7594** [BlankerL/DXY-COVID-19-Data#80]
你好，我想要通过DXYArea.csv查看历史数据。但是里面有一些省份的数据，比如Anhui，并不是每天都更新的，请问怎么样可以拿到过去每天更新的数据呢

**Comment by BlankerL** [comment]
数据并不是每天都更新的，而是每一次丁香园上的数据发生变化之后才有更新。如果当天没有更新，说明丁香园当天并没有更新该省份的疫情数据。

**Comment by BlankerL** [comment]
Duplicate of #68
