### ISSUE TITLE
请问数据是停止更新了么？

### ISSUE THREAD

**Issue by Liorocky** [BlankerL/DXY-COVID-19-Data#81]
请问数据是停止更新了么，已经一天没有更新了。

**Comment by BlankerL** [comment]
Deuplicate of BlankerL/DXY-COVID-19-Crawler#105

---

目前已经恢复更新，正在检查之前的原因，全部合并到此处进行讨论。

**Comment by BlankerL** [comment]
目前数据已经恢复更新。

**Comment by Unicorndy** [comment]
数据好像又停止更新了

**Comment by BlankerL** [comment]
> 数据好像又停止更新了

感谢反馈，今天的状况和昨天不太一样，目前数据过大，DXYArea-TimeSeries.json文件大小超出GitHub限制（100MB）已经无法持续更新了。

---

目前问题已经暂时得到解决，我在本周内会针对这个问题具体进行优化。

同时，会发布一份省级/海外国家级日频数据序列的文件，并在未来持续更新。

**Comment by Unicorndy** [comment]
了解！谢谢你一直继续更新与维持！辛苦了

**Comment by BlankerL** [comment]
您好，数据已经恢复更新，可以参考#96，随后我会说明使用方法。
