### ISSUE TITLE
数据仓库 DXYArea.json 文件内容可能缺失

### ISSUE THREAD

**Issue by ehuo** [BlankerL/DXY-COVID-19-Data#82]
之前是调用 nCoV/api/area?latest=1接口每天对数据进行清洗，由于机器故障所以需要查询历史数据进行重新清洗。需要找全国和国外的疫情历史数据，DXYArea.json文件中会有大量国内省份缺失数据，例如文件中湖北省的疫情数据只有4月27日。像这种情况是4月27日湖北省的数据发生变化，其余时间没有发生变化所以才省略的吗？烦请解惑

**Comment by BlankerL** [comment]
你好，或许你需要的是[DXYArea-TimeSeries.json](https://github.com/BlankerL/DXY-COVID-19-Data/blob/master/json/DXYArea-TimeSeries.json)？DXYArea.json只有当前时间点各个国家/省市的最新数据。

**Comment by ehuo** [comment]
非常感谢
