### ISSUE TITLE
请问历史数据集为什么下载不了

### ISSUE THREAD

**Issue by jackwang123** [BlankerL/DXY-COVID-19-Data#85]

**Comment by BlankerL** [comment]
麻烦具体描述一下问题，哪个数据集下载不了？

**Comment by jackwang123** [comment]
DXY-COVID-19-Data/csv/DXYArea.csv这个download无法访问

**Comment by BlankerL** [comment]
![image](https://user-images.githubusercontent.com/24969376/81499957-8abb4300-9301-11ea-8c66-af1d3ea3f222.png)
