### ISSUE TITLE
数据只有到19日了吗

### ISSUE THREAD

**Issue by MYX-OvO** [BlankerL/DXY-COVID-19-Data#87]
请问时间序列数据停更了吗，我这边显示只到5/19日

**Comment by Unicorndy** [comment]
希望可以及时解决数据停止问题

**Comment by sayaplayer96** [comment]
附议

**Comment by BlankerL** [comment]
感谢反馈。可以参考#81，数据大小已经超过GitHub 100MB的限制，无法继续上传到项目内了。近期我在期末考试，没有充足的时间对文件大小进行优化，目前暂时停止了对DXYArea-TimeSeries.json文件的更新，确保其他数据能正常更新。

**Comment by BlankerL** [comment]
**目前已经恢复数据推送。**

参考#81，由于DXYArea-TimeSeries.json数据大小超过100MB限制，GitHub不允许commit，因此导致文件更新中断。近期我正在期末考试，没有充足的时间来维护代码，目前已经完成的减少文件大小的措施：

1. 取消json文件的所有空格缩进；
2. 移除json文件内空白的`comment`字段。

目前的方案已经将文件大小从100MB减小至70MB，我会在5月29日后更系统地减小文件大小。

**Comment by Allineer** [comment]
@BlankerL, how about DXYArea.json for 19 May - 22 May range? Are they lost?

PS: thanks for you job and good luck with the exam!

**Comment by ak47wj** [comment]
@BlankerL, 有一个简单的做法是以月为单位分割文件，保证单个文件小于100M。

**Comment by BlankerL** [comment]
> @BlankerL, how about DXYArea.json for 19 May - 22 May range? Are they lost?
> 
> 
> 
> PS: thanks for you job and good luck with the exam!

No, they are stored in the database and will not be lost. 

Thank you🤟🏼

**Comment by Allineer** [comment]
@BlankerL, 

> No, they are stored in the database and will not be lost.

In the current DXYArea-TimeSeries.json I see last two updates: from `2020-05-22 04:38:02.190 UTC` and from `2020-05-20 09:06:31.102 UTC`... and no updates in between :(

**Comment by ak47wj** [comment]
DXYArea.csv文件缺少5月21日的数据：
![missing_data_0521](https://user-images.githubusercontent.com/8622493/82797259-689cf580-9ea9-11ea-8bb4-248bfe969cae.png)

**Comment by BlankerL** [comment]
抱歉，已经确认数据确实存在缺失，并且没有合适的解决方案来恢复这部分数据。如果未来找到合适的解决方案会将这部分数据补全。
