### ISSUE TITLE
第一次弄这个不知道怎么操作...

### ISSUE THREAD

**Issue by ssy1004** [BlankerL/DXY-COVID-19-Data#88]
[{'imgUrl': 'https://img1.dxycdn.com/2020/0317/125/3402496596146414521-135.png', 'title': '非湖北新增确诊'}, {'imgUrl': 'https://img1.dxycdn.com/2020/0317/214/3402486670477137705-135.png',

用excel打开来数据是这样显示的。。。

**Comment by BlankerL** [comment]
[这里](https://github.com/BlankerL/DXY-COVID-19-Data/tree/master/csv)才是你需要的数据

**Comment by SiberiaWool** [comment]
请问这个数据怎么下载呀，点了Download以后打开了一个奇怪的网页，里面显示的内容就像ssy1004所说一样。

**Comment by SiberiaWool** [comment]
用客户端clone项目也是每次都失败

**Comment by BlankerL** [comment]
> 请问这个数据怎么下载呀，点了Download以后打开了一个奇怪的网页，里面显示的内容就像ssy1004所说一样。

方便给一个截图吗？

另外，如果在中国大陆直接下载，可能会因为GitHub的DNS被污染而无法下载或者速度奇慢，可以参考#37

**Comment by SiberiaWool** [comment]
刚才又打开了！不好意思，不知道怎么引用图片，大概是这个样子。

dailyPic,dailyPics,summary,countRemark,currentConfirmedCount,confirmedCount,suspectedCount,curedCount,deadCount,seriousCount,suspectedIncr,currentConfirmedIncr,confirmedIncr,curedIncr,deadIncr,seriousIncr,remark1,remark2,remark3,remark4,remark5,note1,note2,note3,generalRemark,abroadRemark,marquee,quanguoTrendChart,hbFeiHbTrendChart,foreignTrendChart,importantForeignTrendChart,foreignTrendChartGlobal,importantForeignTrendChartGlobal,foreignStatistics,globalStatistics,globalOtherTrendChartData,updateTime
"https://img1.dxycdn.com/2020/0211/763/3395998884005602079-135.png,https://img1.dxycdn.com/2020/0211/362/3395998896890788910-135.png,https://img1.dxycdn.com/2020/0211/365/3395998905480724211-135.png,https://img1.dxycdn.com/2020/0211/364/3395998916217859778-135.png,https://img1.dxycdn.com/2020/0211/922/3395998929103046444-135.png,https://img1.dxycdn.com/2020/0211/089/3395998939840182072-135.png","['https://img1.dxycdn.com/2020/0211/763/3395998884005602079-135.png', 'https://img1.dxycdn.com/2020/0211/362/3395998896890788910-135.png', 'https://img1.dxycdn.com/2020/0211/365/3395998905480724211-135.png', 'https://img1.dxycdn.com/2020/0211/364/3395998916217859778-135.png', 'https://img1.dxycdn.com/2020/0211/922/3395998929103046444-135.png', 'https://img1.dxycdn.com/2020/0211/089/3395998939840182072-135.png']",,,134.0,84603,1761,79824,4645,371.0,5.0,3.0,15.0,12.0,0.0,-26.0,易感人群：人群普遍易感。老年人及有基础疾病者感染后病情较重，儿童及婴幼儿也有发病,潜伏期：一般为 3～7 天，最长不超过 14 天，潜伏期内可能存在传染性，其中无症状病例传染性非常罕见,宿主：野生动物，可能为中华菊头蝠,,,病毒：SARS-CoV-2，其导致疾病命名 COVID-19,传染源：新冠肺炎的患者。无症状感染者也可能成为传染源。,传播途径：经呼吸道飞沫、接触传播是主要的传播途径。气溶胶传播和消化道等传播途径尚待明确。,1. 3 月 12 日国家卫健委确诊补订遗漏 12 例确诊病例（非 12 日新增），暂无具体省份信息。 2. 浙江省 12 例外省治愈暂无具体省份信息。,,"[{'id': 2485, 'marqueeLabel': '深痛悼念', 'marqueeContent': '一夜之间两位抗疫医生相继离世', 'marqueeLink': 'https://dxy.me/n8Jwwy'}, {'id': 2486, 'marqueeLabel': '数字新冠', 'marqueeContent': '6 月 1 日，世界因新冠而变', 'marqueeLink': 'https://dxy.me/e9CmsQ'}, {'id': 2487, 'marqueeLabel': '武汉交卷', 'marqueeContent': '990 万检测，300 无症状感染者', 'marqueeLink': 'https://dxy.me/KpuZT3'}]","[{'imgUrl': 'https://img1.dxycdn.com/2020/0324/278/3403801351376518263-135.png', 'title': '新增疑似/新增确诊'}, {'imgUrl': 'https://img1.dxycdn.com/2020/0324/812/3403847865872006755-135.png', 'title': '境外输入'}, {'imgUrl': 'https://img1.dxycdn.com/2020/0324/547/3403847848692336947-135.png', 'title': '现存确

**Comment by SiberiaWool** [comment]
不好意思，是我太蠢了==。发现在最开始的界面就可以下载，打扰了……

**Comment by SiberiaWool** [comment]
不过在您给出的数据连接里，那四个文件的download按钮确实不太好用，一是打开后是一个纯文本的界面，显示很杂乱的内容,（原谅我不会引用图片QAQ），二是有时候根本打不开，按照网上给出的更改host的方法我连上去也时断时续（我在大陆）。此外我用sourcegraph下载了您在数据链接里面给出的四个“csv文件”之一，但下载时发现却是txt格式。

**Comment by BlankerL** [comment]
> 不过在您给出的数据连接里，那四个文件的download按钮确实不太好用，一是打开后是一个纯文本的界面，显示很杂乱的内容,（原谅我不会引用图片QAQ），二是有时候根本打不开，按照网上给出的更改host的方法我连上去也时断时续（我在大陆）。此外我用sourcegraph下载了您在数据链接里面给出的四个“csv文件”之一，但下载时发现却是txt格式。

是的，那个是浏览器的原因。Chrome可能会直接在浏览器内加载文件的内容，可以直接鼠标右键点击另存为就好了。

首页下载按钮也能够下载，但是会把json文件一起下载下来。
