### ISSUE TITLE
大佬，数据是不是从今天就不更新了？？

### ISSUE THREAD

**Issue by 1607449391** [BlankerL/DXY-COVID-19-Data#91]
大佬，数据是不是从今天就不更新了？？API调用超时了。。

**Comment by BlankerL** [comment]
仍然在保持更新，由于今天受到过多请求服务器超过负载又宕机了...很久没有这种情况了，目前正在检查。

**Comment by BlankerL** [comment]
API已经于7月7日恢复，详见[此处](https://github.com/BlankerL/DXY-COVID-19-Crawler/issues/63#issuecomment-586629489)。
