### ISSUE TITLE
已经一个月没有更新数据了，是停更了么？

### ISSUE THREAD

**Issue by liaoshian** [BlankerL/DXY-COVID-19-Data#96]

**Comment by BlankerL** [comment]
非常感谢您对项目的支持，之前由于GitHub上传文件的容量超过限制（100MB），GitHub禁止我向repository里推送新文件，因此我已经重写了这部分的代码，目前新的文件直接推送到release当中（没有文件大小限制），可以在[此处](https://github.com/BlankerL/DXY-COVID-19-Data/releases)查看更新，更新每24小时进行一次。
