### ISSUE TITLE
完全没有历史数据

### ISSUE THREAD

**Issue by just-automatic** [BlankerL/DXY-COVID-19-Data#98]
完全没有历史数据, 最近疫情已经减弱, 数据没有参考价值, 请问历史数据`release`被删除了吗

**Comment by BlankerL** [comment]
您好，可以参考置顶的问题#97，历史数据都放在release里面啦～
比如2020年10月19日的推送：https://github.com/BlankerL/DXY-COVID-19-Data/releases/tag/2020.10.19
我检查了，数据应该是完整的。
