### ISSUE TITLE
历史时间序列数据json文件夹丢失 =(

### ISSUE THREAD

**Issue by enermyfree** [BlankerL/DXY-COVID-19-Data#99]
保存历史数据的json文件夹404了，如果想要使用2019.12-2020.1的数据该去哪找呢
辛苦

**Comment by BlankerL** [comment]
你好，麻烦参考#97，由于GitHub目录太大无法继续推送，因此数据已经被转移到Release里面了。
数据仓库内的数据是从2020年1月22日凌晨开始记录的，所以没有1月22日以前的数据（据我所知，1月22日以前的数据没有一个很统一/公允的数值）
